name: omniscan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  camera: ^0.9.2+2
  file_picker: ^4.0.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.4+1
  cupertino_icons: ^1.0.2
  carousel_slider: ^2.3.1
  firebase_core: ^1.8.0
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_ml_vision: ^0.9.10
  path_provider: ^2.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/images/compress.jpg
    - assets/images/htr.jpg
    - assets/images/merge.jpg
    - assets/images/ocr.png
    - assets/images/scanner.png
    - assets/images/background.jpg
    

    


